runtime: php
vm: true

runtime_config:
  document_root: web

#[START env]
env_variables:
    PUBSUB_TOPIC: projects/surferjeff-php-docs-samples/topics/messageq
    GCLOUD_PROJECT: surferjeff-php-docs-samples
    PUBSUB_SUBSCRIPTION: projects/surferjeff-php-docs-samples/subscriptions/appengineflex2
    PUBSUB_VERIFICATION_TOKEN: qnugiveP
#[END env]